#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
# Autocompletion interface
zstyle ':completion:*' menu select

# Complete aliases
setopt COMPLETE_ALIASES

# Command completion
autoload -U compinit
compinit

source ~/.zsh/aliases.zsh
source ~/.zsh/environment.zsh
